Todolist/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
    path('', views.index),
    path('add_todo/', views.add_todo, name='add'),
    path('delete_todo/<int:task_id>/', views.delete_todo, name='delete'),
    path('complete_todo/<int:task_id>/', views.complete_todo, name='complete'),
    path('edit_todo/<int:task_id>/', views.edit_todo, name='edit')
]

todo/models.py
from django.db import models


class Todo(models.Model):
    text = models.CharField(max_length=255)
    date = models.DateTimeField()
    priority = models.IntegerField(default=1)
    is_complete = models.BooleanField(default=False)


todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from .models import Todo
from django.utils import timezone


def index(request):
    tasks = Todo.objects.all().order_by("is_complete", "-priority", "-date")
    return render(request, 'index.html', {'tasks': tasks})


@csrf_exempt
def add_todo(request):
    task_name = request.POST["task_name"]
    task_priority = request.POST["task_priority"]
    if not task_name:
        tasks = Todo.objects.all().order_by("is_complete", "-priority", "-date")
        context = {
            'tasks': tasks,
            "error_message": "Task name can not be empty!"
        }
        return render(request, 'index.html', context=context)
    Todo.objects.create(text=task_name, date=timezone.now(),
                        priority=task_priority)
    return HttpResponseRedirect("/")


@csrf_exempt
def delete_todo(request, task_id):
    Todo.objects.get(id=task_id).delete()
    return HttpResponseRedirect("/")


@csrf_exempt
def complete_todo(request, task_id):
    task = Todo.objects.get(id=task_id)
    task.is_complete = True
    task.save()
    return HttpResponseRedirect("/")


@csrf_exempt
def edit_todo(request, task_id):
    task = Todo.objects.get(id=task_id)
    task.text = request.POST["view_task_name"]
    task.priority = request.POST["view_task_priority"]
    task.save()
    return HttpResponseRedirect("/")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-light"  style="background-color: #e3f2fd;">
      To Do List
    </nav>
  <div class="container">


    {% block content %}
    {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </div>
  </body>
</html>

todo/templates/edit_task.html
{% extends 'base.html' %}

{% block content %}


<div class="row mt-4">
    <div class="col">
        <h2>Edit Item</h2>
    </div>
</div>
<form class="form-inline" action="edit_todo/" method="post">
    <input type="text" name="task_name" class="form-control mb-2 mr-sm-2"
             id="inlineFormInputName2" placeholder="Type Here">
    <select class="form-control mb-2 mr-sm-2" name="task_priority" id="exampleFormControlSelect1" >
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
    <button type="submit" class="btn btn-primary mb-2">Submit</button>
</form>

<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row">
        </th>
      <td>{{ task.id }}</td>
    </tr>

      <td>{{ task.priority }}</td>
      <th scope="col">
        <form action="edit_todo/{{ task.id }}/" method="post">
            <div class="float-rightcenter">
              <button type="submit" class="btn btn-small btn-danger">Edit</button>
            </div>
        </form>
      </th>
      <td>
        {% if task.is_complete == False %}
        <form action="complete_todo/{{ task.id }}/" method="post">
            <div class="float-center">
                <button type="submit" class="btn btn-small btn-warning">Completed</button>
            </div>
        </form>
        {% else %}
            <div class="float-center">
              <span class="badge badge-success">Completed</span>
            </div>
        {% endif %}
      </td>
      <td>
          <form action="delete_todo/{{ task.id }}/" method="post">
              <div class="float-rightcenter">
                <button type="submit" class="btn btn-small btn-danger">Delete</button>
              </div>
          </form>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

{% endblock %}

todo/templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="row mt-4">
  <div class="col">
    <h2>Manage Your Task Here</h2>
  </div>
</div>
<form class="form-inline" action="{% url 'todolist:add' %}" method="post">
  <div>
    Task Name:
    <input type="text" name="task_name" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2"
      placeholder="Type Here">
  </div>
  <div>
    Priority (low to high):
    <select class="form-control mb-2 mr-sm-2" name="task_priority" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary mb-2">Add Task</button>
</form>
{% if error_message %}
  <div class="alert alert-danger" role="alert">
    {{error_message}}
  </div>
{% endif %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Task Name & Priority</th>
      <th scope="col">Completed</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <th scope="row">{{ task.id }}</th>
      <td>
        <form class="form-inline" action="{% url 'todolist:edit' task.id %}" method="post">
          <div class="form-row">
            <input type="text" class="form-control" id="validationCustom01" name="view_task_name"
              value="{{ task.text }}">
            <input type="text" class="form-control" name="view_task_priority" id="validationCustom02"
              value="{{ task.priority }}">
            <button type="submit" class="btn btn-small btn-info">Edit</button>
          </div>
        </form>
      </td>
      <td>
        {% if task.is_complete == False %}
        <form action="{% url 'todolist:complete' task.id %}" method="post">
          <div class="float-center">
            <button type="submit" class="btn btn-small btn-warning">Completed</button>
          </div>
        </form>
        {% else %}
        <div class="float-center">
          <span class="badge badge-success">Completed</span>
        </div>
        {% endif %}
      </td>
      <td>
        <form action="{% url 'todolist:delete' task.id %}" method="post">
          <div class="float-rightcenter">
            <button type="submit" class="btn btn-small btn-danger">Delete</button>
          </div>
        </form>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>

{% endblock %}